package xnet

import "errors"

var (
	ErrConnectionHanged    = errors.New("connection is hanged")
	ErrConnectionClosed    = errors.New("connection is closed")
	ErrConnectionNotOpened = errors.New("connection is not opened")
	ErrConnectionNotHanged = errors.New("connection is not hanged")
	ErrTooManyConnection   = errors.New("too many connection")

	ErrNil        = errors.New("nil")
	ErrInvalidGID = errors.New("invalid gate id")
	ErrInvalidNID = errors.New("invalid node id")

	ErrNotFoundSession      = errors.New("not found session")
	ErrInvalidSessionKind   = errors.New("invalid session kind")
	ErrReceiveTargetEmpty   = errors.New("the receive target is empty")
	ErrInvalidArgument      = errors.New("invalid argument")
	ErrNotFoundRoute        = errors.New("not found route")
	ErrNotFoundEvent        = errors.New("not found event")
	ErrNotFoundEndpoint     = errors.New("not found endpoint")
	ErrNotFoundUserLocation = errors.New("not found user's location")
	ErrClientShut           = errors.New("client is shut")
	ErrConnectionOpened     = errors.New("connection is opened")

	ErrInvalidDecoder          = errors.New("invalid decoder")
	ErrInvalidScanner          = errors.New("invalid scanner")
	ErrNoOperationPermission   = errors.New("no operation permission")
	ErrInvalidConfigContent    = errors.New("invalid config content")
	ErrNotFoundConfigSource    = errors.New("not found config source")
	ErrInvalidFormat           = errors.New("invalid format")
	ErrIllegalRequest          = errors.New("illegal request")
	ErrIllegalOperation        = errors.New("illegal operation")
	ErrInvalidPointer          = errors.New("invalid pointer")
	ErrNotFoundLocator         = errors.New("not found locator")
	ErrMissingTransporter      = errors.New("missing transporter")
	ErrMissingDiscovery        = errors.New("missing discovery")
	ErrNotFoundServiceAddress  = errors.New("not found service address")
	ErrUnknownError            = errors.New("unknown error")
	ErrClientClosed            = errors.New("client is closed")
	ErrActorExists             = errors.New("actor exists")
	ErrMissingDispatchStrategy = errors.New("missing dispatch strategy")
	ErrUnregisterRoute         = errors.New("unregistered route")
	ErrNotBindActor            = errors.New("not bind actor")
	ErrNotFoundActor           = errors.New("not found actor")
	ErrWriterClosing           = errors.New("writer is closing")
	ErrDeadlineExceeded        = errors.New("deadline exceeded")
	ErrMissingResolver         = errors.New("missing resolver")
)
