// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: envelope.proto

package envelope

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 统一消息头
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                     // 序列
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                     // 用户ID
	GameId        int32                  `protobuf:"varint,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // 游戏id(唯一标识)
	MsgId         string                 `protobuf:"bytes,4,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`     // 消息ID
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`         // 时间戳 - 毫秒
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`              // 版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Header) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Header) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *Header) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Header) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Header) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 客户端输入消息
type InputMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`   // 消息头
	Route         string                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`     // 路由ID
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // 请求体数据(序列化后)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputMessage) Reset() {
	*x = InputMessage{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputMessage) ProtoMessage() {}

func (x *InputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputMessage.ProtoReflect.Descriptor instead.
func (*InputMessage) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *InputMessage) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InputMessage) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *InputMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 服务端输出消息 (响应 / 推送)
type OutputMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`                        // 消息头
	MsgType       uint32                 `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`      // 1: 服务端主动推送, 2: 响应请求
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 当 msgType = 2 时，表示错误码，具体参考: https://alidocs.dingtalk.com/i/nodes/YndMj49yWjEKb466f0A374RP83pmz5aA?utm_scene=team_space&iframeQuery=sheet_range%3Dkgqie6hm_5_3_1_1
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`    // 当 msgType = 2 时，错误提示信息
	MsgTag        string                 `protobuf:"bytes,5,opt,name=msg_tag,json=msgTag,proto3" json:"msg_tag,omitempty"`          // 消息标签
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                            // 业务数据，序列化后
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputMessage) Reset() {
	*x = OutputMessage{}
	mi := &file_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputMessage) ProtoMessage() {}

func (x *OutputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputMessage.ProtoReflect.Descriptor instead.
func (*OutputMessage) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *OutputMessage) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *OutputMessage) GetMsgType() uint32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *OutputMessage) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *OutputMessage) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *OutputMessage) GetMsgTag() string {
	if x != nil {
		return x.MsgTag
	}
	return ""
}

func (x *OutputMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\benvelope\"\x94\x01\n" +
	"\x06Header\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\x05R\x06gameId\x12\x15\n" +
	"\x06msg_id\x18\x04 \x01(\tR\x05msgId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"h\n" +
	"\fInputMessage\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.envelope.HeaderR\x06header\x12\x14\n" +
	"\x05route\x18\x02 \x01(\tR\x05route\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xbd\x01\n" +
	"\rOutputMessage\x12(\n" +
	"\x06Header\x18\x01 \x01(\v2\x10.envelope.HeaderR\x06Header\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\rR\amsgType\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\x12\x17\n" +
	"\amsg_tag\x18\x05 \x01(\tR\x06msgTag\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04dataB\x15Z\x13./envelope;envelopeb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_envelope_proto_goTypes = []any{
	(*Header)(nil),        // 0: envelope.Header
	(*InputMessage)(nil),  // 1: envelope.InputMessage
	(*OutputMessage)(nil), // 2: envelope.OutputMessage
}
var file_envelope_proto_depIdxs = []int32{
	0, // 0: envelope.InputMessage.header:type_name -> envelope.Header
	0, // 1: envelope.OutputMessage.Header:type_name -> envelope.Header
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
