// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: room.proto

package envelope

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomInfo_State int32

const (
	RoomInfo_WAITING RoomInfo_State = 0 // 等待中
	RoomInfo_LOADING RoomInfo_State = 1 // 加载中 (玩家准备就绪，游戏程序准备中; 视具体游戏而定)
	RoomInfo_GAMING  RoomInfo_State = 2 // 游戏中
	RoomInfo_OVER    RoomInfo_State = 3 // 结束
)

// Enum value maps for RoomInfo_State.
var (
	RoomInfo_State_name = map[int32]string{
		0: "WAITING",
		1: "LOADING",
		2: "GAMING",
		3: "OVER",
	}
	RoomInfo_State_value = map[string]int32{
		"WAITING": 0,
		"LOADING": 1,
		"GAMING":  2,
		"OVER":    3,
	}
)

func (x RoomInfo_State) Enum() *RoomInfo_State {
	p := new(RoomInfo_State)
	*p = x
	return p
}

func (x RoomInfo_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomInfo_State) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[0].Descriptor()
}

func (RoomInfo_State) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[0]
}

func (x RoomInfo_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomInfo_State.Descriptor instead.
func (RoomInfo_State) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 0}
}

type RoomReadyRequest_Action int32

const (
	RoomReadyRequest_READY        RoomReadyRequest_Action = 0 // 准备
	RoomReadyRequest_CANCEL_READY RoomReadyRequest_Action = 1 // 取消准备
)

// Enum value maps for RoomReadyRequest_Action.
var (
	RoomReadyRequest_Action_name = map[int32]string{
		0: "READY",
		1: "CANCEL_READY",
	}
	RoomReadyRequest_Action_value = map[string]int32{
		"READY":        0,
		"CANCEL_READY": 1,
	}
)

func (x RoomReadyRequest_Action) Enum() *RoomReadyRequest_Action {
	p := new(RoomReadyRequest_Action)
	*p = x
	return p
}

func (x RoomReadyRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomReadyRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[1].Descriptor()
}

func (RoomReadyRequest_Action) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[1]
}

func (x RoomReadyRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomReadyRequest_Action.Descriptor instead.
func (RoomReadyRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{11, 0}
}

// 房间配置
type RoomConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxMemberNum  uint32                 `protobuf:"varint,1,opt,name=max_member_num,json=maxMemberNum,proto3" json:"max_member_num,omitempty"`                                      // 最大成员数量
	RoomType      int32                  `protobuf:"varint,2,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`                                                    // 房间类型 (各游戏自行解释, e.g. 0-普通房, 1-VIP房)
	Mode          int32                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`                                                                            // 模式 (各游戏自行解释)
	GameId        int32                  `protobuf:"varint,4,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                                                          // 游戏ID
	MinMemberNum  uint32                 `protobuf:"varint,5,opt,name=min_member_num,json=minMemberNum,proto3" json:"min_member_num,omitempty"`                                      // 最小成员数量 (至少需要多少人开始游戏)
	Extra         map[string]*Value      `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomConfig) Reset() {
	*x = RoomConfig{}
	mi := &file_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomConfig) ProtoMessage() {}

func (x *RoomConfig) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomConfig.ProtoReflect.Descriptor instead.
func (*RoomConfig) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (x *RoomConfig) GetMaxMemberNum() uint32 {
	if x != nil {
		return x.MaxMemberNum
	}
	return 0
}

func (x *RoomConfig) GetRoomType() int32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *RoomConfig) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *RoomConfig) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *RoomConfig) GetMinMemberNum() uint32 {
	if x != nil {
		return x.MinMemberNum
	}
	return 0
}

func (x *RoomConfig) GetExtra() map[string]*Value {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 房间信息
type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                                          // 房间ID
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`                                                     // 房间名称
	Config        *RoomConfig            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`                                                                         // 房间配置
	Members       []*Member              `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`                                                                       // 成员列表
	CreateTime    int64                  `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                                              // 创建时间 ms
	UpdateTime    int64                  `protobuf:"varint,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`                                              // 更新时间 ms
	State         RoomInfo_State         `protobuf:"varint,7,opt,name=state,proto3,enum=envelope.RoomInfo_State" json:"state,omitempty"`                                             // 状态
	Extra         map[string]*Value      `protobuf:"bytes,8,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomInfo) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomInfo) GetConfig() *RoomConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RoomInfo) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RoomInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *RoomInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *RoomInfo) GetState() RoomInfo_State {
	if x != nil {
		return x.State
	}
	return RoomInfo_WAITING
}

func (x *RoomInfo) GetExtra() map[string]*Value {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 登录游戏请求
type LoginGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginGameRequest) Reset() {
	*x = LoginGameRequest{}
	mi := &file_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGameRequest) ProtoMessage() {}

func (x *LoginGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGameRequest.ProtoReflect.Descriptor instead.
func (*LoginGameRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

// 登录响应数据
type LoginGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`                     // 玩家信息
	RoomInfo      *RoomInfo              `protobuf:"bytes,2,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"` // 牌桌信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginGameResponse) Reset() {
	*x = LoginGameResponse{}
	mi := &file_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGameResponse) ProtoMessage() {}

func (x *LoginGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGameResponse.ProtoReflect.Descriptor instead.
func (*LoginGameResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{3}
}

func (x *LoginGameResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *LoginGameResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

// 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{4}
}

// 快速匹配 [请求]
type QuickMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          int32                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`                                                                            // 模式 (各游戏自行解释)
	Extra         map[string]*Value      `protobuf:"bytes,2,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickMatchRequest) Reset() {
	*x = QuickMatchRequest{}
	mi := &file_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickMatchRequest) ProtoMessage() {}

func (x *QuickMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickMatchRequest.ProtoReflect.Descriptor instead.
func (*QuickMatchRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{5}
}

func (x *QuickMatchRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *QuickMatchRequest) GetExtra() map[string]*Value {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 快速匹配 [响应]
type QuickMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,1,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"` // 房间信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickMatchResponse) Reset() {
	*x = QuickMatchResponse{}
	mi := &file_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickMatchResponse) ProtoMessage() {}

func (x *QuickMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickMatchResponse.ProtoReflect.Descriptor instead.
func (*QuickMatchResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{6}
}

func (x *QuickMatchResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

// 创建房间 [请求]
type RoomCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          int32                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"` // 模式 (各游戏自行解释)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreateRequest) Reset() {
	*x = RoomCreateRequest{}
	mi := &file_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateRequest) ProtoMessage() {}

func (x *RoomCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateRequest.ProtoReflect.Descriptor instead.
func (*RoomCreateRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{7}
}

func (x *RoomCreateRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// 创建房间 [响应]
type RoomCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,1,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"` // 房间快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreateResponse) Reset() {
	*x = RoomCreateResponse{}
	mi := &file_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateResponse) ProtoMessage() {}

func (x *RoomCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateResponse.ProtoReflect.Descriptor instead.
func (*RoomCreateResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{8}
}

func (x *RoomCreateResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

// 加入房间 [请求]
type RoomJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间ID
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`            // 房间密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinRequest) Reset() {
	*x = RoomJoinRequest{}
	mi := &file_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinRequest) ProtoMessage() {}

func (x *RoomJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinRequest.ProtoReflect.Descriptor instead.
func (*RoomJoinRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{9}
}

func (x *RoomJoinRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomJoinRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 加入房间 [响应]
type RoomJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,1,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"` // 房间快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinResponse) Reset() {
	*x = RoomJoinResponse{}
	mi := &file_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinResponse) ProtoMessage() {}

func (x *RoomJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinResponse.ProtoReflect.Descriptor instead.
func (*RoomJoinResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{10}
}

func (x *RoomJoinResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

// 准备/取消准备 [请求]
type RoomReadyRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	RoomId        int64                   `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                   // 房间ID
	SeatId        int64                   `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`                   // 座位ID
	Act           RoomReadyRequest_Action `protobuf:"varint,3,opt,name=act,proto3,enum=envelope.RoomReadyRequest_Action" json:"act,omitempty"` // 操作类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomReadyRequest) Reset() {
	*x = RoomReadyRequest{}
	mi := &file_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomReadyRequest) ProtoMessage() {}

func (x *RoomReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomReadyRequest.ProtoReflect.Descriptor instead.
func (*RoomReadyRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{11}
}

func (x *RoomReadyRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomReadyRequest) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *RoomReadyRequest) GetAct() RoomReadyRequest_Action {
	if x != nil {
		return x.Act
	}
	return RoomReadyRequest_READY
}

// 准备/取消准备 [响应]
type RoomReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomReadyResponse) Reset() {
	*x = RoomReadyResponse{}
	mi := &file_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomReadyResponse) ProtoMessage() {}

func (x *RoomReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomReadyResponse.ProtoReflect.Descriptor instead.
func (*RoomReadyResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{12}
}

// 退出房间 [请求]
type RoomExitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomExitRequest) Reset() {
	*x = RoomExitRequest{}
	mi := &file_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomExitRequest) ProtoMessage() {}

func (x *RoomExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomExitRequest.ProtoReflect.Descriptor instead.
func (*RoomExitRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{13}
}

func (x *RoomExitRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 退出房间 [响应]
type RoomExitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomExitResponse) Reset() {
	*x = RoomExitResponse{}
	mi := &file_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomExitResponse) ProtoMessage() {}

func (x *RoomExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomExitResponse.ProtoReflect.Descriptor instead.
func (*RoomExitResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{14}
}

// 踢出玩家 [请求]
type KickPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`       // 房间ID
	SeatId        int32                  `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`       // 座位ID (视具体游戏而定)
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家ID (视具体游戏而定)
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                      // 踢出原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerRequest) Reset() {
	*x = KickPlayerRequest{}
	mi := &file_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerRequest) ProtoMessage() {}

func (x *KickPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerRequest.ProtoReflect.Descriptor instead.
func (*KickPlayerRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{15}
}

func (x *KickPlayerRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *KickPlayerRequest) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *KickPlayerRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *KickPlayerRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 踢出玩家 [响应]
type KickPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerResponse) Reset() {
	*x = KickPlayerResponse{}
	mi := &file_room_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerResponse) ProtoMessage() {}

func (x *KickPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerResponse.ProtoReflect.Descriptor instead.
func (*KickPlayerResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{16}
}

var File_room_proto protoreflect.FileDescriptor

const file_room_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"room.proto\x12\benvelope\x1a\fmember.proto\x1a\vvalue.proto\"\xa4\x02\n" +
	"\n" +
	"RoomConfig\x12$\n" +
	"\x0emax_member_num\x18\x01 \x01(\rR\fmaxMemberNum\x12\x1b\n" +
	"\troom_type\x18\x02 \x01(\x05R\broomType\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\x05R\x04mode\x12\x17\n" +
	"\agame_id\x18\x04 \x01(\x05R\x06gameId\x12$\n" +
	"\x0emin_member_num\x18\x05 \x01(\rR\fminMemberNum\x125\n" +
	"\x05extra\x18\x06 \x03(\v2\x1f.envelope.RoomConfig.ExtraEntryR\x05extra\x1aI\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.envelope.ValueR\x05value:\x028\x01\"\xc5\x03\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12,\n" +
	"\x06config\x18\x03 \x01(\v2\x14.envelope.RoomConfigR\x06config\x12*\n" +
	"\amembers\x18\x04 \x03(\v2\x10.envelope.MemberR\amembers\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x06 \x01(\x03R\n" +
	"updateTime\x12.\n" +
	"\x05state\x18\a \x01(\x0e2\x18.envelope.RoomInfo.StateR\x05state\x123\n" +
	"\x05extra\x18\b \x03(\v2\x1d.envelope.RoomInfo.ExtraEntryR\x05extra\x1aI\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.envelope.ValueR\x05value:\x028\x01\"7\n" +
	"\x05State\x12\v\n" +
	"\aWAITING\x10\x00\x12\v\n" +
	"\aLOADING\x10\x01\x12\n" +
	"\n" +
	"\x06GAMING\x10\x02\x12\b\n" +
	"\x04OVER\x10\x03\"\x12\n" +
	"\x10LoginGameRequest\"n\n" +
	"\x11LoginGameResponse\x12(\n" +
	"\x06member\x18\x01 \x01(\v2\x10.envelope.MemberR\x06member\x12/\n" +
	"\troom_info\x18\x02 \x01(\v2\x12.envelope.RoomInfoR\broomInfo\"\x12\n" +
	"\x10HeartbeatRequest\"\xb0\x01\n" +
	"\x11QuickMatchRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x05R\x04mode\x12<\n" +
	"\x05extra\x18\x02 \x03(\v2&.envelope.QuickMatchRequest.ExtraEntryR\x05extra\x1aI\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.envelope.ValueR\x05value:\x028\x01\"E\n" +
	"\x12QuickMatchResponse\x12/\n" +
	"\troom_info\x18\x01 \x01(\v2\x12.envelope.RoomInfoR\broomInfo\"'\n" +
	"\x11RoomCreateRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x05R\x04mode\"E\n" +
	"\x12RoomCreateResponse\x12/\n" +
	"\troom_info\x18\x01 \x01(\v2\x12.envelope.RoomInfoR\broomInfo\"F\n" +
	"\x0fRoomJoinRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"C\n" +
	"\x10RoomJoinResponse\x12/\n" +
	"\troom_info\x18\x01 \x01(\v2\x12.envelope.RoomInfoR\broomInfo\"\xa0\x01\n" +
	"\x10RoomReadyRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\x03R\x06seatId\x123\n" +
	"\x03act\x18\x03 \x01(\x0e2!.envelope.RoomReadyRequest.ActionR\x03act\"%\n" +
	"\x06Action\x12\t\n" +
	"\x05READY\x10\x00\x12\x10\n" +
	"\fCANCEL_READY\x10\x01\"\x13\n" +
	"\x11RoomReadyResponse\"*\n" +
	"\x0fRoomExitRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"\x12\n" +
	"\x10RoomExitResponse\"z\n" +
	"\x11KickPlayerRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\x05R\x06seatId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x14\n" +
	"\x12KickPlayerResponseB\x15Z\x13./envelope;envelopeb\x06proto3"

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData []byte
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)))
	})
	return file_room_proto_rawDescData
}

var file_room_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_room_proto_goTypes = []any{
	(RoomInfo_State)(0),          // 0: envelope.RoomInfo.State
	(RoomReadyRequest_Action)(0), // 1: envelope.RoomReadyRequest.Action
	(*RoomConfig)(nil),           // 2: envelope.RoomConfig
	(*RoomInfo)(nil),             // 3: envelope.RoomInfo
	(*LoginGameRequest)(nil),     // 4: envelope.LoginGameRequest
	(*LoginGameResponse)(nil),    // 5: envelope.LoginGameResponse
	(*HeartbeatRequest)(nil),     // 6: envelope.HeartbeatRequest
	(*QuickMatchRequest)(nil),    // 7: envelope.QuickMatchRequest
	(*QuickMatchResponse)(nil),   // 8: envelope.QuickMatchResponse
	(*RoomCreateRequest)(nil),    // 9: envelope.RoomCreateRequest
	(*RoomCreateResponse)(nil),   // 10: envelope.RoomCreateResponse
	(*RoomJoinRequest)(nil),      // 11: envelope.RoomJoinRequest
	(*RoomJoinResponse)(nil),     // 12: envelope.RoomJoinResponse
	(*RoomReadyRequest)(nil),     // 13: envelope.RoomReadyRequest
	(*RoomReadyResponse)(nil),    // 14: envelope.RoomReadyResponse
	(*RoomExitRequest)(nil),      // 15: envelope.RoomExitRequest
	(*RoomExitResponse)(nil),     // 16: envelope.RoomExitResponse
	(*KickPlayerRequest)(nil),    // 17: envelope.KickPlayerRequest
	(*KickPlayerResponse)(nil),   // 18: envelope.KickPlayerResponse
	nil,                          // 19: envelope.RoomConfig.ExtraEntry
	nil,                          // 20: envelope.RoomInfo.ExtraEntry
	nil,                          // 21: envelope.QuickMatchRequest.ExtraEntry
	(*Member)(nil),               // 22: envelope.Member
	(*Value)(nil),                // 23: envelope.Value
}
var file_room_proto_depIdxs = []int32{
	19, // 0: envelope.RoomConfig.extra:type_name -> envelope.RoomConfig.ExtraEntry
	2,  // 1: envelope.RoomInfo.config:type_name -> envelope.RoomConfig
	22, // 2: envelope.RoomInfo.members:type_name -> envelope.Member
	0,  // 3: envelope.RoomInfo.state:type_name -> envelope.RoomInfo.State
	20, // 4: envelope.RoomInfo.extra:type_name -> envelope.RoomInfo.ExtraEntry
	22, // 5: envelope.LoginGameResponse.member:type_name -> envelope.Member
	3,  // 6: envelope.LoginGameResponse.room_info:type_name -> envelope.RoomInfo
	21, // 7: envelope.QuickMatchRequest.extra:type_name -> envelope.QuickMatchRequest.ExtraEntry
	3,  // 8: envelope.QuickMatchResponse.room_info:type_name -> envelope.RoomInfo
	3,  // 9: envelope.RoomCreateResponse.room_info:type_name -> envelope.RoomInfo
	3,  // 10: envelope.RoomJoinResponse.room_info:type_name -> envelope.RoomInfo
	1,  // 11: envelope.RoomReadyRequest.act:type_name -> envelope.RoomReadyRequest.Action
	23, // 12: envelope.RoomConfig.ExtraEntry.value:type_name -> envelope.Value
	23, // 13: envelope.RoomInfo.ExtraEntry.value:type_name -> envelope.Value
	23, // 14: envelope.QuickMatchRequest.ExtraEntry.value:type_name -> envelope.Value
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	file_member_proto_init()
	file_value_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		EnumInfos:         file_room_proto_enumTypes,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
