// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: room_player.proto

package envelope

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家信息
type RoomPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                              // 玩家ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                                                                     // 昵称
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                                                                         // 头像
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                                                                        // 性别
	SeatId        int32                  `protobuf:"varint,5,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`                                                          // 座位ID
	IsReady       bool                   `protobuf:"varint,6,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`                                                       // 已准备?
	Extra         map[string]*Value      `protobuf:"bytes,7,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomPlayer) Reset() {
	*x = RoomPlayer{}
	mi := &file_room_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayer) ProtoMessage() {}

func (x *RoomPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_room_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayer.ProtoReflect.Descriptor instead.
func (*RoomPlayer) Descriptor() ([]byte, []int) {
	return file_room_player_proto_rawDescGZIP(), []int{0}
}

func (x *RoomPlayer) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RoomPlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoomPlayer) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RoomPlayer) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *RoomPlayer) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *RoomPlayer) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *RoomPlayer) GetExtra() map[string]*Value {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_room_player_proto protoreflect.FileDescriptor

const file_room_player_proto_rawDesc = "" +
	"\n" +
	"\x11room_player.proto\x12\benvelope\x1a\vvalue.proto\"\xa0\x02\n" +
	"\n" +
	"RoomPlayer\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12\x17\n" +
	"\aseat_id\x18\x05 \x01(\x05R\x06seatId\x12\x19\n" +
	"\bis_ready\x18\x06 \x01(\bR\aisReady\x125\n" +
	"\x05extra\x18\a \x03(\v2\x1f.envelope.RoomPlayer.ExtraEntryR\x05extra\x1aI\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.envelope.ValueR\x05value:\x028\x01B\x15Z\x13./envelope;envelopeb\x06proto3"

var (
	file_room_player_proto_rawDescOnce sync.Once
	file_room_player_proto_rawDescData []byte
)

func file_room_player_proto_rawDescGZIP() []byte {
	file_room_player_proto_rawDescOnce.Do(func() {
		file_room_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_player_proto_rawDesc), len(file_room_player_proto_rawDesc)))
	})
	return file_room_player_proto_rawDescData
}

var file_room_player_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_room_player_proto_goTypes = []any{
	(*RoomPlayer)(nil), // 0: envelope.RoomPlayer
	nil,                // 1: envelope.RoomPlayer.ExtraEntry
	(*Value)(nil),      // 2: envelope.Value
}
var file_room_player_proto_depIdxs = []int32{
	1, // 0: envelope.RoomPlayer.extra:type_name -> envelope.RoomPlayer.ExtraEntry
	2, // 1: envelope.RoomPlayer.ExtraEntry.value:type_name -> envelope.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_room_player_proto_init() }
func file_room_player_proto_init() {
	if File_room_player_proto != nil {
		return
	}
	file_value_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_player_proto_rawDesc), len(file_room_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_player_proto_goTypes,
		DependencyIndexes: file_room_player_proto_depIdxs,
		MessageInfos:      file_room_player_proto_msgTypes,
	}.Build()
	File_room_player_proto = out.File
	file_room_player_proto_goTypes = nil
	file_room_player_proto_depIdxs = nil
}
