// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: value.proto

package envelope

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任意类型值统一封装
// oneof 表示只能选择其中一个类型赋值
// 适用于扩展字段,如Player的extra字段
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_Str
	//	*Value_I32
	//	*Value_I64
	//	*Value_U32
	//	*Value_U64
	//	*Value_Bytes
	//	*Value_F32
	//	*Value_F64
	//	*Value_Bool
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetStr() string {
	if x != nil {
		if x, ok := x.Value.(*Value_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Value) GetI32() int32 {
	if x != nil {
		if x, ok := x.Value.(*Value_I32); ok {
			return x.I32
		}
	}
	return 0
}

func (x *Value) GetI64() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_I64); ok {
			return x.I64
		}
	}
	return 0
}

func (x *Value) GetU32() uint32 {
	if x != nil {
		if x, ok := x.Value.(*Value_U32); ok {
			return x.U32
		}
	}
	return 0
}

func (x *Value) GetU64() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Value_U64); ok {
			return x.U64
		}
	}
	return 0
}

func (x *Value) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Value.(*Value_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *Value) GetF32() float32 {
	if x != nil {
		if x, ok := x.Value.(*Value_F32); ok {
			return x.F32
		}
	}
	return 0
}

func (x *Value) GetF64() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_F64); ok {
			return x.F64
		}
	}
	return 0
}

func (x *Value) GetBool() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_Bool); ok {
			return x.Bool
		}
	}
	return false
}

type isValue_Value interface {
	isValue_Value()
}

type Value_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3,oneof"` // 字符串
}

type Value_I32 struct {
	I32 int32 `protobuf:"varint,2,opt,name=i32,proto3,oneof"` // 有符号32位整数
}

type Value_I64 struct {
	I64 int64 `protobuf:"varint,3,opt,name=i64,proto3,oneof"` // 有符号64位整数
}

type Value_U32 struct {
	U32 uint32 `protobuf:"varint,4,opt,name=u32,proto3,oneof"` // 无符号32位整数
}

type Value_U64 struct {
	U64 uint64 `protobuf:"varint,5,opt,name=u64,proto3,oneof"` // 无符号64位整数
}

type Value_Bytes struct {
	Bytes []byte `protobuf:"bytes,6,opt,name=bytes,proto3,oneof"` // 字节数组
}

type Value_F32 struct {
	F32 float32 `protobuf:"fixed32,7,opt,name=f32,proto3,oneof"` // 32位浮点数
}

type Value_F64 struct {
	F64 float64 `protobuf:"fixed64,8,opt,name=f64,proto3,oneof"` // 64位浮点数
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,9,opt,name=bool,proto3,oneof"` // 布尔值
}

func (*Value_Str) isValue_Value() {}

func (*Value_I32) isValue_Value() {}

func (*Value_I64) isValue_Value() {}

func (*Value_U32) isValue_Value() {}

func (*Value_U64) isValue_Value() {}

func (*Value_Bytes) isValue_Value() {}

func (*Value_F32) isValue_Value() {}

func (*Value_F64) isValue_Value() {}

func (*Value_Bool) isValue_Value() {}

var File_value_proto protoreflect.FileDescriptor

const file_value_proto_rawDesc = "" +
	"\n" +
	"\vvalue.proto\x12\benvelope\"\xca\x01\n" +
	"\x05Value\x12\x12\n" +
	"\x03str\x18\x01 \x01(\tH\x00R\x03str\x12\x12\n" +
	"\x03i32\x18\x02 \x01(\x05H\x00R\x03i32\x12\x12\n" +
	"\x03i64\x18\x03 \x01(\x03H\x00R\x03i64\x12\x12\n" +
	"\x03u32\x18\x04 \x01(\rH\x00R\x03u32\x12\x12\n" +
	"\x03u64\x18\x05 \x01(\x04H\x00R\x03u64\x12\x16\n" +
	"\x05bytes\x18\x06 \x01(\fH\x00R\x05bytes\x12\x12\n" +
	"\x03f32\x18\a \x01(\x02H\x00R\x03f32\x12\x12\n" +
	"\x03f64\x18\b \x01(\x01H\x00R\x03f64\x12\x14\n" +
	"\x04bool\x18\t \x01(\bH\x00R\x04boolB\a\n" +
	"\x05valueB\x15Z\x13./envelope;envelopeb\x06proto3"

var (
	file_value_proto_rawDescOnce sync.Once
	file_value_proto_rawDescData []byte
)

func file_value_proto_rawDescGZIP() []byte {
	file_value_proto_rawDescOnce.Do(func() {
		file_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_value_proto_rawDesc), len(file_value_proto_rawDesc)))
	})
	return file_value_proto_rawDescData
}

var file_value_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_value_proto_goTypes = []any{
	(*Value)(nil), // 0: envelope.Value
}
var file_value_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_value_proto_init() }
func file_value_proto_init() {
	if File_value_proto != nil {
		return
	}
	file_value_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_Str)(nil),
		(*Value_I32)(nil),
		(*Value_I64)(nil),
		(*Value_U32)(nil),
		(*Value_U64)(nil),
		(*Value_Bytes)(nil),
		(*Value_F32)(nil),
		(*Value_F64)(nil),
		(*Value_Bool)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_value_proto_rawDesc), len(file_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_value_proto_goTypes,
		DependencyIndexes: file_value_proto_depIdxs,
		MessageInfos:      file_value_proto_msgTypes,
	}.Build()
	File_value_proto = out.File
	file_value_proto_goTypes = nil
	file_value_proto_depIdxs = nil
}
